### ISSUE TITLE
Update the database prior to #1Lib1Ref

### ISSUE THREAD

**Issue by Halibutt** [eggpi/citationhunt#102]
Hi all. I have absolutely no clue about the technical side of things. However, prior to next years' #1Lib1Ref drive, we're adding plenty of {{fact}} tags to articles on Polish Wikipedia. Would it be possible to update the database before 15 January, to make those new tags findable in Citation Hunt?

**Comment by eggpi** [comment]
Hi, sure! The databases actually get updated automatically every 4 days, for all languages, so it definitely will happen a few times before Jan 15th. For what it's worth, the last update for plwiki was on Dec 24th, so the next will be on the 28th.
