### ISSUE TITLE
Articles without any reference?

### ISSUE THREAD

**Issue by symac** [eggpi/citationhunt#103]
Hello,
as part of #1lib1ref I am currently using a lot citationhunt, thanks for the great work. I was just wondering if it wouldn't be a good idea to add an option to search for articles without any reference, not only the ones with a "citation needed" template. 

I strongly believe that an article with 0 reference needs to be completed and if citationhunt was able to add an option to spot these articles that would be a great enhancement!

**Comment by eggpi** [comment]
Hey, thanks a lot for the suggestion! I've been hearing quite a few ideas about ways CH could be more general and have different modes of operation. Most notably, issue #100 seems related to what you've suggested, in that we'd have this general tool for browsing worklists of articles, and "articles with 0 references" could be one such worklist.

In general, I totally agree that a tool for browsing more problematic articles like that would be great, though I'm not convinced that tool should be CH itself, as I'd like to keep it relatively focused and beginner-friendly, both in the way it's used and in the kinds of edits you can do through it.

But yeah, a more general CH is definitely something I have in mind, and hopefully we can get to that in the following months -- either in CH itself or a separate tool as we figure out how to make these suggestions fit together.

**Comment by eggpi** [comment]
An update: the worklist tool is one of the [Google Summer of Code 2018](http://summerofcode.withgoogle.com/) projects for Wikipedia, so there's a good chance that it will happen mid-year! The project is described in more detail [here](https://phabricator.wikimedia.org/T187305). Closing this issue now as that's where discussions should go from now on.
