### ISSUE TITLE
[[Wikimedia:Citationhunt-leaderboard description/ko]] i18n issue

### ISSUE THREAD

**Issue by revi** [eggpi/citationhunt#104]
The original texts reads...

>These are users that fixed the most snippets through %s in the past %s days. Well done!

Is first `%s` and second `%s` differentiated via the order of appearance? (So, first `%s` always mean "snippets ~" and second `%s` always mean "`%s` days"?) If I would do translation without the text feel like a translation, I need to make second `%s` to come first.

----

* **URL**: https://translatewiki.net/wiki/Wikimedia:Citationhunt-leaderboard description/ko
* Exported from [T191898](https://phabricator.wikimedia.org/T191898)

**Comment by eggpi** [comment]
Hi @revi! The first `%s` gets replaced with the name of the tool ("Citation Hunt" by default, but some languages like to translated it using the `tooltitle` string), and the second `%s` is the number of days.

Given that, do you still need to invert the order? If so, it shouldn't be too hard to make them unordered. I'm actually a little surprised this hasn't come up before with other languages. Just let me know!

**Comment by revi** [comment]
That now makes sense. While it would be great if it was unordered, I think I managed to make it natural while preserving the order.

Thanks!

**Comment by eggpi** [comment]
No problem, thank you for translating and for bringing this up!

By the way, to actually add a new language to Citation Hunt, we'll need a little more information about it (see our [Meta page](https://meta.wikimedia.org/wiki/Citation_Hunt#Adding_support_to_a_new_language), or issue #96 as an example).

If you have that information, please file an issue with it once you're done translating the UI, and it should be pretty easy from there.
