### ISSUE TITLE
Please add Nepali Language Support for using with ne.wikipedia.org

### ISSUE THREAD

**Issue by sarojdhakal** [eggpi/citationhunt#106]
Hi Team,

I've completely localized citation hunt in translatewiki.net in Nepali. 

- We are looking forward to organizing 1Lib1Ref in Nepal

Please help add Nepali language and Wikipedia project support.

Thanks,
Saroj

**Comment by takot** [comment]
Hi @sarojdhakal 

Could you add `ne = { ... }` section in config.py as other language settings do?

**Comment by eggpi** [comment]
Hey @sarojdhakal -- sure, happy to add it! Basically we need to add an entry to [our config](https://github.com/eggpi/citationhunt/blob/master/config.py) as @takot said. You can do it yourself and send me a pull request, or give us a little more information about newiki and I'll add the config for you. See [our Meta page](https://meta.wikimedia.org/wiki/Citation_Hunt#Adding_support_to_a_new_language) for how this works.

**Comment by eggpi** [comment]
Closing out incomplete, old language requests. Please reopen if you have the information we need!
