### ISSUE TITLE
argument order of 'leaderboard_description'

### ISSUE THREAD

**Issue by takot** [eggpi/citationhunt#107]
In en.json, it describes 
`"leaderboard_description": "These are users that fixed the most snippets through %s in the past %s days. Well done!",`
The first `%s` anticipates "Citation Hunt", while the second `%s` does a number like "30".
On the other hand, 
`"leaderboard_description": "こちらの利用者が過去%s日間に%sを使い、最も多くのスニペットを解決しました。おめでとうございます!",`
is the description of Japanese in ja.json.
In this translation, the former `%s` presumes "30" while the latter one does "Citation Hunt". As a result, this variable is called in [templates/leaderboard.html](https://github.com/eggpi/citationhunt/blob/master/templates/leaderboard.html) and [current Japanese leaderboard](https://tools.wmflabs.org/citationhunt/ja/leaderboard.html) looks an odd sentence.

I'm considering how to resolve this.

1. Changes the translation on [translatewiki](https://translatewiki.net/w/i.php?title=Special:Translate&group=citationhunt&language=ja&filter=translated&action=translate). Fortunately Japanese is somewhat flexible language in terms of word order. This would be a practical answer for now, however, leaving the code as it is might cause the same problem in future in some other languages that are strict to the word order.
1. `tooltitle` have not been translated in many languages, actually. Just removing one `%s`, using only one `%s` and making the code simpler might be another idea. But this may take quite a few coding regarding *.json and other files.

How do y'all think?

**Comment by takot** [comment]
Doing 1. immediately, and thinking the option of 2. may be a good answer, possibly.

**Comment by eggpi** [comment]
Hmm, yeah, I think we should change the string itself. It's not the first time this has come up for this string (see #104). It's pretty interesting that this one created problems but `instructions_details`, which has 3 `%s`, did not.

Anyway, I think we could do the same as in [`instructions_goal`](https://github.com/eggpi/citationhunt/blob/6437c1007fd931b8e7015fec1861a2bca06171ea/chstrings/en.json#L4), where we use unordered formatters then use [`str.format`](https://github.com/eggpi/citationhunt/blob/8692fb3020db81d944c837a3fc8abc5be3792d78/chstrings/__init__.py#L51) in the code to make up the final string. Does that make sense?

**Comment by takot** [comment]
Yeah, that would by far make sense, I bet.

**Comment by takot** [comment]
Confirmed the code. Much appreciated!
