### ISSUE TITLE
Hungarian language support

### ISSUE THREAD

**Issue by AdamHarangozo** [eggpi/citationhunt#108]
Could you please add Hungarian language to the tool? The interface is already translated. Thanks!

Language code: hu
Category for articles with citation needed tags: Kategória:Forrással nem rendelkező lapok
A link to a tutorial page on how to add references: Wikipédia:Jegyzetelés
Names of the templates that are used to mark unsourced statements: {{nincs forrás}}, {{forráskérő}}, {{Részben nincs forrás}}, {{rossz forrás}}, {{vitatott forrás}}
The category used for Hidden categories: Kategória:Rejtett kategóriák
Language writing direction: left-to-right

**Comment by eggpi** [comment]
Hi, sure, I'm setting this up now. Should go live in a couple of hours. Thanks!
