### ISSUE TITLE
kowiki is broken

### ISSUE THREAD

**Issue by eggpi** [eggpi/citationhunt#122]
https://tools.wmflabs.org/citationhunt/ko just returns 500, and from the logs it looks like the reason is that we simply don't have any snippets to serve.

Looking at the [Wikipedia category we pull articles from](https://ko.wikipedia.org/wiki/%EB%B6%84%EB%A5%98:%EB%AC%B8%EC%9E%A5%EC%97%90_%EC%B6%9C%EC%B2%98%EA%B0%80_%ED%95%84%EC%9A%94%ED%95%9C_%EA%B8%80) in the config, it seems to only have 2 articles, so that's not surprising. 

Hey @kht1992 , do you know if we're using the wrong category here?

**Comment by revi** [comment]
Probably should collect from **subcategories** of https://ko.wikipedia.org/wiki/%EB%B6%84%EB%A5%98:%EC%B6%9C%EC%B2%98%EA%B0%80_%ED%95%84%EC%9A%94%ED%95%9C_%EA%B8%80.

**Comment by eggpi** [comment]
Perfect, thank you!
