### ISSUE TITLE
Document custom Citation Hunt.

### ISSUE THREAD

**Issue by eggpi** [eggpi/citationhunt#124]
In #119 we added a new feature that allows users to create and share "custom" Citation Hunts. It's still experimental at this point, but if it proves to be useful, we should document its usage, likely in the [Meta page for Citation Hunt](https://meta.wikimedia.org/wiki/Citation_Hunt).

**Comment by Samwalton9** [comment]
Added some documentation on Meta: https://meta.wikimedia.org/w/index.php?title=Citation_Hunt&type=revision&diff=18752738&oldid=18226878 :)

**Comment by eggpi** [comment]
That looks great, thank you very much!
