### ISSUE TITLE
No cutomise option available unless it's en-us

### ISSUE THREAD

**Issue by uyscuti-wiki** [eggpi/citationhunt#132]
The customise option is hidden/doesn't work when the default browser language is set to 'English (United Kingdom)' and I assume that's the case for other versions of English (non-us). The tool should maybe show the option for all versions of English and (or) allow explicit selection of en-us.

**Comment by eggpi** [comment]
Hey, thanks for reporting! I think we're just lacking the en-gb versions of the strings for the UI (in chstrings/en-gb.json). For example, we do show the option in Spanish: https://tools.wmflabs.org/citationhunt/es

Interestingly, it looks like we _used to_ have those strings, but they got removed in a TranslateWiki update:

https://github.com/eggpi/citationhunt/commit/e9aa19b6e4a0a6b5d288eabbe132f48cafc954b1#diff-6c788379043f36444869a08556479f3a

@translatewiki @Nikerabbit any idea why that happened?

Anyway, I think we can just re-add the strings either manually or through TranslateWiki.

**Comment by Nikerabbit** [comment]
Sorry, I have no idea what you are talking about. Which are the relevant message keys?

**Comment by eggpi** [comment]
Sorry, should have mentioned them explicitly.

I mean the strings in en-gb.json that I added in
https://github.com/eggpi/citationhunt/commit/af65785c3486829b1dacbbc688a0a8baa59912e7,
then removed in the TranslateWiki export I linked above.

For a specific example, the string with key "customize" is one of those.

If I'm reading it right (I'm on my phone right now and for the next 3 days
so it's a bit harder to tell), in my commit, I'm both adding strings and
reformatting the file to replace tabs with spaces. I wonder if that caused
some trouble in TranslateWiki?

But as I said above, happy to just add the strings back if this is all
working as intended.

**Comment by Nikerabbit** [comment]
Something definitely went amiss with those strings, as they were not imported in translatewiki.net.
My first thought is that happened because they looked like duplicates of English strings and because of that they were ignored during import.

Do you have a fallback system in place, so that missing messages are taken from en.json if missing from en-gb.json?

**Comment by eggpi** [comment]
Unfortunately no, we just don't show UI elements when the corresponding
string is missing. I am thinking of adding that fallback in issue #123
though.

**Comment by Nikerabbit** [comment]
Well, in that case the strings should be added again.

**Comment by uyscuti-wiki** [comment]
Thanks for the fixing this promptly.
