### ISSUE TITLE
[Translatewiki] Improve string documentation & use meaningful link anchors

### ISSUE THREAD

**Issue by Abijeet** [eggpi/citationhunt#136]
Clubbing two issues reported on Translatewiki.net regarding message documentation and link anchors.
# Improve message documentation
Link to comment: https://translatewiki.net/wiki/Thread:Support/About_Wikimedia:Citationhunt-custom_please_wait/nl
Related Translation: https://translatewiki.net/wiki/Wikimedia:Citationhunt-custom_notice/en
> This string should be documented.
As well as at least all other strings of this product that have parameters.
Please also add parameter support, and a check. 

# Use meaningful link anchors
Link to comment: https://translatewiki.net/wiki/Thread:Support/About_Wikimedia:Citationhunt-custom_notice/nl
Related Translation: https://translatewiki.net/wiki/Wikimedia:Citationhunt-custom_notice/en
> Please use meaningful link anchors. "Click here" isn't that.

**Comment by eggpi** [comment]
Hi, thanks for reporting this!

I imagine the required documentation is an entry in qqq.json for those strings?

And I don't think I follow what "parameter support" and "check" are referring to. Any documentation I should go read?

**Comment by Abijeet** [comment]
> I imagine the required documentation is an entry in qqq.json for those strings?
Yes, correct.

In the translation,
> You are browsing a custom {tooltitle} with a limited list of articles. {link_start}Click here{link_end} to go to unrestricted {tooltitle}. 

`{tooltitle}`, `{link_start}`, `{link_end}` are the parameters. These do not change between translations, and hence we have something called [insertables](https://www.mediawiki.org/wiki/Help:Extension:Translate/Insertables) that can be configured so that translators don't have to type these out each time.

In addition, a **checker** will try to ensure that the translator are using these parameters by warning them if the their translations do not have them. We can also convert the warnings into errors, in which case translators will not be allowed to save the translations if these parameters are missing.

I can help you in doing this. Let me know if,

1. You'd like these to be added.
2. If a parameter is missing, would you like it to be a warning or an error?

**Comment by eggpi** [comment]
Hey, sorry this took me so long. I've just made the changes to qqq.json, let me know if you need anything else please.

Also, yes, please add the checker, and yes, all should be an error.

**Comment by eggpi** [comment]
Hey @Abijeet , it looks like the export in 3d865ae3527361ead3e8a664c1f172eb078ae8f7 is reverting my additions to qqq.json, or at least removing some of them. Is that intended?
