### ISSUE TITLE
citationhunt/ja returns Internal Server Error

### ISSUE THREAD

**Issue by takot** [eggpi/citationhunt#139]
I'm not sure why but currently production environment for Japanese Wikipedia
https://tools.wmflabs.org/citationhunt/ja
returns Internal Server Error. At least this has been persisting since August 18 circa.

**Comment by takot** [comment]
As far as I tried, these four languages versions also returns 500.
https://tools.wmflabs.org/citationhunt/nl
https://tools.wmflabs.org/citationhunt/pl
https://tools.wmflabs.org/citationhunt/pt
https://tools.wmflabs.org/citationhunt/ca

**Comment by eggpi** [comment]
Wow this is embarrassing. Thank you for reporting!

I'm seeing an empty database on Toolforge:

```
select snippet from s52481__citationhunt_pl.snippets limit 1;                                                                                                                           Empty set (0.00 sec)
```

and I think it's because, for some reason, we're failing to expand the top-level category for articles containing {{cn}}:

```
$ CH_LANG=pl www/python/venv/bin/python3.5 citationhunt/scripts/print_unsourced_pageids_from_wikipedia.py
```

**Comment by eggpi** [comment]
Oh, I think I got it. It's a regression from the Python3 migration. Fix on the way.

**Comment by takot** [comment]
Thank you for immediate work! Really appreciated.
