### ISSUE TITLE
Petscans with Wikidata IDs should convert to appropriate local Wiki

### ISSUE THREAD

**Issue by Sadads** [eggpi/citationhunt#142]
User story: you want to run a multilingual campaign for a topic like Human Rights (http://petscan1.wmflabs.org/?psid=12744266) and you want folks to be able to use the same "base list" to drive participation in multiple languages. The best way to do this is a Wikidata query that can be captured in a tool like Petscan (i.e. http://petscan1.wmflabs.org/?psid=12744266). But teaching each and every organizer in each language how to use Petscann is a pain. 

Citation Hunt should be able to detect if the petscan id is returning Wikidata PageIDs or QiDs and if so, automatically call the Wikidata API for the language that Petscan is operating in at the time (i.e English etc): https://tools.wmflabs.org/citationhunt/en?custom=7335e0f0

**Comment by eggpi** [comment]
> Citation Hunt should be able to detect if the petscan id is returning Wikidata PageIDs or QiDs and if so, automatically call the Wikidata API for the language that Petscan is operating in at the time (i.e English etc)

I imagine you'd want this to be the language that Citation Hunt is using, no? That is, you can import the same PetScan query into Citation Hunt in whatever language, and it gets properly resolved?

I wonder if this would make sense as a feature in PetScan itself? That is, when querying PetScan to turn a PSID into articles, Citation Hunt could pass a parameter for resolving QIDs into articles in the specified language?

This could also make sense in the PetScan UI: a checkbox for an Output option like "Resolve SPARQL results into articles", which then uses the Language and Project to do the translation. The link from Citation Hunt to PetScan would then pre-populate that option as we do for language.

I don't mind doing that translation in Citation Hunt, but it feels like supporting it in PetScan would be more natural (as it's "just" an output option for the existing query) and of course allows other tools to benefit from it.

@magnusmanske thoughts?

**Comment by Sadads** [comment]
I agree that it might make sense on petscan's end :) It would make a lot sense.

**Comment by magnusmanske** [comment]
OK, first, _please_ don't use the petscan1 server, just petscan (V2).

Now, if you want a "base query" that outputs different "target wikis" on demand, just use the psid as a "base query", and add the target wiki to the URL parameters, like so:
```
https://petscan.wmflabs.org/?psid=12744266&common_wiki=other&common_wiki_other=itwiki
```
That works for all other parameters as well; it will load the psid query, then overwrite the additional parameters. Use `&format=json` to get machine-readable output etc.

**Comment by eggpi** [comment]
That's awesome, thank you Magnus! It seems like CH can just pass those two extra parameters whenever importing a PSID. I'll do that now.

**Comment by eggpi** [comment]
@Sadads please give it a try. I've just tested it by importing your sample query into CH in Spanish, which resulted in a custom CH of 148 articles: https://tools.wmflabs.org/citationhunt/es?custom=22dbc886.

**Comment by Sadads** [comment]
Yeah it seems to work great!
