### ISSUE TITLE
Create intersections by searching for articles

### ISSUE THREAD

**Issue by eggpi** [eggpi/citationhunt#146]
We have a search bar in the UI for browsing through categories. It would be cool if that search bar were smarter, like allowing the user to search article titles and snippet contents too.

**Comment by eggpi** [comment]
I've thought about this one some more and I can see a few things we can try:

1. The search bar allows searching the titles of articles in addition to categories (of course, it must be clear whether a search result is an article or category). When the user clicks an article title, they are redirected to one snippet inside that article (and then they're browsing at random again). It's not clear to me what should happen if there are multiple snippets in the article.
2. Same as 1, but clicking an article automatically creates and redirects the user to a custom CH with the snippets of that article.
3. Same as 1, but there are checkboxes next to each article result. The user can check which articles they want, and click a button to create and browse to a custom CH with those articles.

So 1 is the least powerful one, but it's also the simplest and should help users who simply want to find an article without even having to learn what a custom CH is. On the other hand, if this hypothetical user already has an article in mind, they might as well just go to it and look for {{cn}}, bypassing CH.

2 is a bit more useful but might get confusing to users, since they now need to learn what a custom CH is.

3 definitely sounds useful, but at that point I almost feel like it should be part of the custom CH wizard rather than a feature of the search bar. That is, it's just a more convenient way of creating a custom CH by searching and adding existing articles.

@SamWalton9 @Sadads I wonder if you have any thoughts on what we should do here?

**Comment by eggpi** [comment]
Having thought about this some more, I think something like option 3 is the one that makes more sense for now, so I'm going with that in the [smart](https://github.com/eggpi/citationhunt/tree/smart/) branch. We do need a simpler way to create intersections. Here's a demo:

![](https://thumbs.gfycat.com/YawningFewKite-size_restricted.gif)

Of course, now that we have this UI, it makes a few other improvements possible, such as using it to edit the results of a PetScan query when creating a custom CH or actually implementing options 1 or 2 above, but I feel like this is the thing that brings most value right now to make custom CH easier to use.

**Comment by Sadads** [comment]
So one option, could be to generate articles like they are doing with the http://recommend-large.wmflabs.org/ -- it uses a "seed" article and runs it through the mediawiki search, and then returns articles that meet the criteria for the tool (i.e. needs to be translated from English to Swedish). You could use a similar criteria for yours.

**Comment by eggpi** [comment]
Huh, that is an interesting idea. Let me file #155 to track that, it's a good feature idea but for this issue I think I'll just go ahead with option 3 as above.
