### ISSUE TITLE
Implement more Wikipedia templates.

### ISSUE THREAD

**Issue by eggpi** [eggpi/citationhunt#15]
We currently [implement](https://github.com/guilherme-pg/citationhunt/blob/79b0a08785055a31af1f1c6c6e60f07fb83c7d46/scripts/snippet_parser.py#L22,L44) a selected set of Wikipedia templates and tags, and just remove the contents of the rest. In particular, for templates that are usually transcluded inside parenthesis, we sometimes end up with [empty](https://citationhunt.herokuapp.com/?id=d2c03e03&cat=all) [parenthesis](https://citationhunt.herokuapp.com/?id=3e0d159f&cat=all) in our snippets.

It's not a good idea to try to implement every single Wikipedia template, but it could be nice to support a few more to properly parse a larger set of articles. For example, implementing [Template:Lang](https://en.wikipedia.org/wiki/Template:Lang) looks pretty easy, and this is a very widely employed template. [Template:Chem](https://en.wikipedia.org/wiki/Template:Chem), on the other hand, may not be worth it.

**Comment by guilherme-pg** [comment]
Another pathological case: https://tools.wmflabs.org/citationhunt/?id=1437f569&cat=all . This has `IPA-en`, `IPAc-en` and `lang`, plus regular text, inside parenthesis.

**Comment by guilherme-pg** [comment]
Using [Parsoid](https://www.mediawiki.org/wiki/Parsoid) might help us support all of Wikipedia's templates. Basically we'd find and clean up snippets like we do now, except keeping all templates. Then the snippets can be run through Parsoid to generate the final HTML.

[Here's the list of other parsers for reference](https://www.mediawiki.org/wiki/Alternative_parsers), but Parsoid sounds like the best choice here in terms of compatibility with MediaWiki.

**Comment by Aubreymcfato** [comment]
Hi, a question: is there a way this great tool can be configured for languages? I'd love to be able to use Italian Wikipedia or similar.

**Comment by eggpi** [comment]
Hi Andrea, I've never tried other languages, and, while the code does assume English in [a few places](https://github.com/eggpi/citationhunt/blob/master/scripts/parse_pages_articles.py#L40), I think it shouldn't be terribly hard to adapt it and get decent results. If you're interested in trying, I'll be happy to answer any questions you might have, and review/merge the changes you'll need to make.

I'd start by creating another issue (let's keep this one about English templates), and trying to follow the instructions for [generating the database locally](https://github.com/eggpi/citationhunt/blob/master/scripts/README.md#generating-the-database-locally) on a dump of the Italian Wikipedia.

**Comment by pepato** [comment]
I comment just to follow up on this.

**Comment by eggpi** [comment]
The German version (#55) uses the Wikipedia API to handle templates, and that seems to work very well. I think extending that approach to other languages is the way to go. That will be a pretty big refactor of the snippet parser, but it seems like it's what we should have done all along, and I have some ideas for how to do it.

**Comment by eggpi** [comment]
This is a duplicate of #81 at this point.
