### ISSUE TITLE
{link_start} and {link_end} is not translated into link properly in Japanese

### ISSUE THREAD

**Issue by takot** [eggpi/citationhunt#153]
{link_start} and {link_end} appears as they are on /ja. For example,
[https://tools.wmflabs.org/citationhunt/ja?id=455ed483](https://tools.wmflabs.org/citationhunt/ja?id=455ed483). Is this the same one as #136 ?

**Comment by eggpi** [comment]
Oh interesting, thanks for reporting!

Unfortunately the way we use placeholders for our strings is a bit of a mess right now, but basically we expect `instructions_details` to have **either** 3 `%s`, so one of them gets replaced with the `beginners_link`, **or** 2 `%s` and a `{link_start}`/`{link_end}` pair, and everything inside that pair gets replaced with the `beginners_link`.

It looks like for Japanese we have all of the above? https://github.com/eggpi/citationhunt/blob/master/chstrings/ja.json#L26

Would you maybe be able to fix this in TranslateWiki, so it will get fixed when the strings are next imported here please?

**Comment by takot** [comment]
Thanks for looking into it. OK, I will go to Translatewiki and take a look at it.

**Comment by takot** [comment]
Seems this one: [https://translatewiki.net/w/i.php?title=Wikimedia:Citationhunt-instructions_details/ja&action=edit](https://translatewiki.net/w/i.php?title=Wikimedia:Citationhunt-instructions_details/ja&action=edit)

**Comment by takot** [comment]
Updated. [https://translatewiki.net/w/i.php?title=Wikimedia:Citationhunt-instructions_details/ja&diff=next&oldid=9236582](https://translatewiki.net/w/i.php?title=Wikimedia:Citationhunt-instructions_details/ja&diff=next&oldid=9236582)

**Comment by eggpi** [comment]
I've just updated the translation and it looks like this is fixed, thank you!
