### ISSUE TITLE
Make 'good' categories more likely to be chosen.

### ISSUE THREAD

**Issue by eggpi** [eggpi/citationhunt#17]
Categories that describe their articles well should be more likely to be chosen by `assign_categories.py` than those that don't. For example, it would be more desirable to categorize [Vogue (Madonna song)](https://en.wikipedia.org/wiki/Vogue_%28Madonna_song%29) under "Madonna (entertainer) songs" than, say, "Singles certified silver by the Syndicat National de l'Édition Phonographique".

One simple way to detect how well a category describes an article would be to count the occurrences of each word of the category's title in the article's title and text, and normalize that by the length (in words) of the category's title. This score (for all pages belonging to each category) can then be taken into account in our set-cover heuristic somehow.

**Comment by TheInterior** [comment]
Eggpi - awesome service.  But I agree that the category tool needs work, and could drastically improve its usefulness.  This is very non-technical advice, but I'll outline a problem.  My topic area of interest is the Canadian province of British Columbia.  Unfortunately, the tool won't let me select the broad top-level category: "Category:British Columbia", but instead offers only three "bottom-level" categories within that cat.  Any way to get the broader categories in play?

**Comment by eggpi** [comment]
Thanks a lot for your comment! Picking higher-level categories is certainly something I want to explore at some point, but this is quite tricky to do in general, given how complex Wikipedia's category graph is. 

"High schools in British Columbia" and "Unincorporated settlements in British Columbia", for example, are separated by three and four degrees of ancestry from "British Columbia", respectively. There are lots of interesting ways to approach this problem, but it is far from trivial to make an algorithm smart enough to pick the "correct" category in that and similar cases.

The simplest approach I can think of, which is to have a hand curated selection of categories, quickly becomes unwieldy as the set of indexed pages changes and we introduce support for other languages, each with their own categories (I'm working on that right now).

All that is to say, I'd love to experiment with this eventually (or work with someone who is willing to), but I probably won't get to it in the near future.

**Comment by Sadads** [comment]
This sounds like a Wikidata and Tagging problem -- one that most people in our community haven't done good evaluation of yet.

**Comment by Halibutt** [comment]
Just pinging to see if anything changed. The reason is I noticed that many high-level categories where high-visibility articles reside are a no-go, the search window doesn't pick them up at all, while some others are picked up just fine. For instance you can chose "II wojna światowa" in Polish (World War II), but you can't chose "Powstanie listopadowe" (November Uprising) in the same way, even though both are fairly high up the tree. Any ideas?

**Comment by eggpi** [comment]
Unfortunately no, `assign_categories.py` is still using the same algorithm for picking categories. I think something like my initial comment should be fairly easy to implement, though, and I think I can give it a try over the weekend. The result would still be a heuristic though, and we'll inevitably still drop interesting categories.

In the longer term, I think it would make sense to just be far more liberal in the choices of categories, and have the search box dynamically query the server for autocomplete suggestions (right now the full list of categories is sent to the browser and processed locally). That would take more work, but can be an incremental change on top of the better existing heuristics.

**Comment by Halibutt** [comment]
Doesn't HotCat do precisely that? If so, the code should already be there, right? It's simple, but it works.

**Comment by eggpi** [comment]
Oh interesting, I didn't really know HotCat. Actually I think you're right, it doesn't look terribly hard to store and search through all categories, if they have at least a couple of articles lacking citations. I'm trying that.

**Comment by eggpi** [comment]
Branch [categories](https://github.com/eggpi/citationhunt/tree/categories) has the changes for this. It should index most categories (pretty much any that has at least 2 snippets) and the search actually queries the server dynamically.

I deployed it to see how it behaves on Tools Labs before merging. Polish, Spanish and Hebrew are already using more categories; English should follow tomorrow. Take a look if you get a chance, I'll likely merge this tomorrow night if I don't find any major problems :)
