### ISSUE TITLE
Adding more Wikipedia CEE languages

### ISSUE THREAD

**Issue by zblace** [eggpi/citationhunt#175]
How hard is it to enable new languages? It would be great if you can enable not just Serbian and Croatian, but also SerboCroatian and Bosnian (think differences should not be significant) in next week or two.

**Comment by eggpi** [comment]
Hi, the documentation for adding a new language is at https://meta.wikimedia.org/wiki/Citation_Hunt#Internationalization_and_Localization and we'll need a bit of information about the relevant Wikis.

I can't promise I'll be able to get to it in the next couple of weeks, but if I have what I need, it will happen eventually :) Alternatively, if you want to try the technical way and send a pull request, I should be able to review it more quickly.

**Comment by eggpi** [comment]
Both are done:

https://citationhunt.toolforge.org/bs
https://citationhunt.toolforge.org/sh

**Comment by zblace** [comment]
Thank zou for sorting this out!
