### ISSUE TITLE
Dark mode

### ISSUE THREAD

**Issue by Wdmiscool** [eggpi/citationhunt#181]
Hey, I'm kinda new to github so this probably isn't the place to ask.
But I would love it if someone made a darkmode version of this. I like editing wikipedia before bed but I don't like it when I have to work with all this light. (fun fact: wikipedia has dark mode)

**Comment by eggpi** [comment]
Cool idea, thanks! And yes, this is the right place to ask.

This could be a good issue for a new contributor interested in frontend stuff (CSS). I'm a bit busy at the moment but I can come back to this if there are no takers after a while.

**Comment by eggpi** [comment]
I'm giving this a try, see WIP screenshot:

<img width="1440" alt="Screenshot 2023-01-31 at 16 43 39" src="https://user-images.githubusercontent.com/489134/215825294-5780433c-2b67-4b55-99c8-39c370c808b9.png">

**Comment by eggpi** [comment]
I've pushed this to production now, if you'd like to give it a try! The option to switch themes is under the hamburguer menu at the top of the page.
