### ISSUE TITLE
Add simplewiki

### ISSUE THREAD

**Issue by bennylin** [eggpi/citationhunt#187]
Could you add Simple English Wikipedia (simple.wikipedia.org) on the list of wikis?

**Comment by bennylin** [comment]
When I visited "https://citationhunt.toolforge.org/simple" or selecting Simple English from the dropdown, it automatically redirect to "https://citationhunt.toolforge.org/en/simple". Where did the config go wrong?

**Comment by eggpi** [comment]
Oh, sorry, I just forgot something when deploying this last night: I needed to [launch a job](https://github.com/eggpi/citationhunt/blob/master/scripts/README.md#manually-launch-a-job) that actually reads simplewiki and finds the snippets.

I've done that now, but I think it might take a few hours. I'll check again later today.

**Comment by bennylin** [comment]
Ah ok, I will close PR 189

**Comment by eggpi** [comment]
https://citationhunt.toolforge.org/simple should be working now. Thank you!
