### ISSUE TITLE
Locked articles

### ISSUE THREAD

**Issue by silviaegt** [eggpi/citationhunt#199]
Dear @eggpi !
We had an amazing hour with #1Lib1Ref Organizers from the all over the world and everyone was super thankful about your tool. We had two remarks that might make the tool even cooler! So let me know what you think (I'll do a ticket/issue for each one of them in the hopes that makes it easier)
So one participant that uses the English version of the tool said that sometimes the missing citation is found in a [protected Wikipedia article ](https://en.wikipedia.org/wiki/Wikipedia:Lists_of_protected_pages) since the #1Lib1Ref campaign attracts many newbies, this is not ideal as they do not quite understand why they can't improve the page with a reference. Do you think this is something that could be changed?

**Comment by eggpi** [comment]
Hi Silvia, thank you for the kind words and I'm glad you found this tool useful!

I think it does make sense to filter protected pages out of Citation Hunt. On an implementation note, it looks pretty easy to detect protected pages with the [page_restrictions](https://www.mediawiki.org/wiki/Manual:Page_restrictions_table) table.

Until I get to that, a workaround for #1Lib1Ref organizers is to use the [customize feature](https://meta.wikimedia.org/wiki/Citation_Hunt#Customize) to create a custom Citation Hunt without protected pages.

For English Wikipedia, this can be achieved by importing a PetScan query that computes the pages in [Category:All_articles_with_unsourced_statements](https://en.wikipedia.org/wiki/Category:Wikipedia_protected_pages) _excluding_ those in [Category:Wikipedia_protected_pages](https://en.wikipedia.org/wiki/Category:Wikipedia_protected_pages). Here's a link to an [example query](https://petscan.wmflabs.org/?langs_labels_yes=&project=wikipedia&outlinks_any=&maxlinks=&sitelinks_no=&interface_language=en&search_max_results=500&wikidata_prop_item_use=&ores_prediction=any&show_disambiguation_pages=both&depth=2&rxp_filter=&search_filter=&ns%5B0%5D=1&sparql=&cb_labels_no_l=1&cb_labels_yes_l=1&links_to_all=&subpage_filter=either&page_image=any&labels_no=&common_wiki_other=&edits%5Bbots%5D=both&show_soft_redirects=both&negcats=Wikipedia_protected_pages&wpiu=any&templates_any=&since_rev0=&after=&categories=All_articles_with_unsourced_statements&cb_labels_any_l=1&min_redlink_count=1&wikidata_label_language=&referrer_name=&language=en&pagepile=&common_wiki=auto&source_combination=&search_wiki=&max_sitelink_count=) in PetScan.

**Comment by silviaegt** [comment]
That's a very clever workaround @eggpi ! If you get to implement that, would you let me know, so I can let organizers know?

**Comment by eggpi** [comment]
I think this should be fixed at this point: we should be excluding protected pages in all languages and the workaround is no longer needed. Please do let me know if you still find a protected page, I'm happy to take another look.
