### ISSUE TITLE
Issue with the refresh rate of the French version?

### ISSUE THREAD

**Issue by Facetiae** [eggpi/citationhunt#201]
Hi!

There seems to be an issue with the refresh rate of the French version. 

**Example:** Martin Lessard's article, form the "Écrivain québécois" category, is still referenced here but the last modification as been done more than four days ago on the article (on Octobrer 23rd). 

https://citationhunt.toolforge.org/fr?id=3e46ef34&cat=077d5cbf
https://fr.wikipedia.org/w/index.php?title=Martin_Lessard&action=history

For the same category, and wanting to verify if there was an issue, I added a "réf. souhaitée" tag on André Carpentier's article: https://fr.wikipedia.org/w/index.php?title=Andr%C3%A9_Carpentier&action=history. 

It still doesn't show up on Citation Hunt. I thought I'd let you know.

Thanks,

Ben

**Comment by eggpi** [comment]
Hi, thanks for reporting this!

We actually update the database every 4 days for most languages, so some delay is expected. However, I also see this database update job has been broken for a few months (!), so let me fix that.

**Comment by eggpi** [comment]
I've verified that the update is now fixed, and now your first link (correctly) no longer exists.

Also, just for reference, you can now find these two snippets corresponding to your test edit:

- https://citationhunt.toolforge.org/fr?id=59b7ed35
- https://citationhunt.toolforge.org/fr?id=edf64534

**Comment by Facetiae** [comment]
Hi @eggpi,

That's great! Thanks for the quick fix :)
