### ISSUE TITLE
Use live databases instead of the pages-articles dump.

### ISSUE THREAD

**Issue by eggpi** [eggpi/citationhunt#40]
It might be possible to adapt the database generation scripts so that we query the [revision](https://www.mediawiki.org/wiki/Manual:Revision_table) and [text](https://www.mediawiki.org/wiki/Manual:Text_table) tables to get the wikicode for articles.

This way it should be possible to rebuild the database more often (we're currently limited by the frequency of dumps), while still keeping most of the current scripts intact, especially the algorithm for choosing categories.

**Comment by ricordisamoa** [comment]
Sadly [the text table is not replicated on Tool Labs](//wikitech.wikimedia.org/wiki/Help:Tool_Labs/Database#Redacted_tables).

**Comment by eggpi** [comment]
Bummer, but thanks for the link! I guess I can look into using the API instead.

For my own later reference, it looks like it's possilbe to just [query index.php](https://www.mediawiki.org/wiki/API:FAQ#get_the_content_of_a_page_.28wikitext.29.3F) with the right parameters to do what I need. However, something like a batch API query might be more polite:

```
https://en.wikipedia.org/w/api.php?action=query&pageids=37807608|45188030|9429841&prop=revisions&rvprop=content&format=json
```
