### ISSUE TITLE
Handle wikicode in section titles

### ISSUE THREAD

**Issue by eggpi** [eggpi/citationhunt#47]
Sometimes, the titles of sections contain simple wikicode for things like italics. For example, the article on [The San Diego Union-Tribune](https://en.wikipedia.org/wiki/The_San_Diego_Union-Tribune) has a section called **Acquisition of the _North County Times_**, for which the wikicode is `===Acquisition of the ''North County Times''===`.

We use the names of sections to try to infer the anchor for its paragraph so we can link directly to it. In this example, we want our code to be able to transform the wikicode into  `Acquisition_of_the_North_County_Times` so we can produce a link such as https://en.wikipedia.org/wiki/The_San_Diego_Union-Tribune#Acquisition_of_the_North_County_Times.

The current version of this code is in a function called `section_name_to_anchor` in [scripts/parse_live.py](https://github.com/eggpi/citationhunt/blob/master/scripts/parse_live.py#L50), and it produces the wrong anchor: instead of just `Acquisition_of_the_North_County_Times`, we end up with `Acquisition_of_the_.27.27North_County_Times.27.27`, because we're failing to remove the single-quotes before calling `urllib.quote(...)`.

I think the best way to make this work is to have the snippet parser remove the wikicode from section titles. That is, we should do something like <pre><code>section.get(0).title.<b>strip_code()</b>.strip()</code></pre> [here](https://github.com/eggpi/citationhunt/blob/e3fc57761ae518f1d0357fe24ae2b16a084e3cb9/snippet_parser/snippet_parser.py#L56), before the title of the section gets returned to `section_name_to_anchor` (I'm not sure the second `strip` will be even needed). Then this can be covered by a unit test in [snippet_parser/en_test.py](https://github.com/eggpi/citationhunt/blob/master/snippet_parser/en_test.py).

**Comment by karmadolkar** [comment]
Hello @eggpi ! Can I try this one?

**Comment by eggpi** [comment]
Sure, please do and send me a pull request when ready!

**Comment by karmadolkar** [comment]
I understood that we need to remove the single quotes since they are being parsed as .27. I cloned the repository & set up the virtualenv, but I can't seem to find snippet_parser.py in the snippet_py folder. Could you help me out here, please? @eggpi

**Comment by eggpi** [comment]
Yeah, I filed this issue a long time ago, and I moved the code a little since then.

For the solution I proposed, the relevant code is in snippet_parser/core.py:
https://github.com/eggpi/citationhunt/blob/b69afbee8ed4555853687a975f3807cd9f1154df/snippet_parser/core.py#L274

snippet_parser is the package that converts articles into snippets. It is invoked by scripts/parse_live.py, which writes the snippets into our database.

snippet_parser returns the section titles to parse_live, and currently it's possible for those section titles to contain Wiki markup, which causes this issue. parse_live uses that section name to figure out what anchor to use when linking to the article:
https://github.com/eggpi/citationhunt/blob/b69afbee8ed4555853687a975f3807cd9f1154df/scripts/parse_live.py#L64-L73

I think we should guarantee that snippet_parser doesn't return titles that have Wiki markup, by adding a `strip_code()` call as I suggested above.

By the way, there's also a handy script in the scripts/ directory to invoke snippet_parser on an individual article. That can help you test this by hand, if you want:

```
$ CH_LANG=en scripts/parse_page.py The_San_Diego_Union-Tribune --output=raw
Section: Acquisition of the ''North County Times''
   <div class="ch-snippet"><p><i>U-T San Diego</i> bought the <i>North County
   Times</i> in 2012.<sup>[1]</sup> On October 15, 2012, the <i>North County
   Times</i> ceased publication and became the <i>U-T North County Times</i>, which
   was an edition of the <i>U-T</i> with some North County–specific
   content.<sup>[2]</sup> Six months later the <i>U-T North County Times</i> name
   was dropped and the newspaper became a North County edition of the
   <i>U-T</i>.<span class="ch-cn-marker"><sup>[<i><span title="This claim needs
   references to reliable sources. (May 2015)">citation
   needed</span></i>]</sup></span> </p> </div>
.
```

as you can imagine, we want no quotes in the "Section" line in the output above.
