### ISSUE TITLE
Handle templates that redirect to {{citation needed}}

### ISSUE THREAD

**Issue by eggpi** [eggpi/citationhunt#51]
It seems possible to use the [redirect table](https://www.mediawiki.org/wiki/Manual:Redirect_table) to figure out that, say, `{{cn}}` is the same as `{{Citation needed}}`, instead of having to specify all redirects manually [in the config](https://github.com/eggpi/citationhunt/blob/bbad3fed6295d4e92418a6df0b7ccc6af230d7fa/config.py#L33).

**Comment by Sadads** [comment]
You might want to check out what they did for https://tools.wmflabs.org/redirectviews/ . They seem to handle redirects from any page, super easily.
