### ISSUE TITLE
German version

### ISSUE THREAD

**Issue by eggpi** [eggpi/citationhunt#55]
A German version will take a bit more work, as the German Wikipedia doesn't use inline references. The idea here would be to just use the first paragraph of the article as a snippet, and update the strings in the UI accordingly (that is, "The Wikipedia article", not "The Wikipedia snippet").

I guess the code changes would be to allow the German version to use a different `extract_snippets` function in the `snippet_parser` package, somehow, then have that extract lead sections. I _think_ the remainder of the code should be unaffected.

Optionally, we might want to preserve the **bold** text in the lead section, since it indicates the main topic of the article. This will also require a bit of refactoring, as right now the snippets are stored in the database without any kind wikicode (we drop the bold markup in the snippet parser).

**Comment by eggpi** [comment]
I've tried this a bit in https://github.com/eggpi/citationhunt/commit/ce4c8186ca0219bd7c982239ae321d6892f458c1. It looks OK, but not great: for one, the lead section tends to contain a bunch of templates that CH doesn't handle, so we end up with lots of broken snippets; also, chopping off the first paragraph of the lead results in some rather strange, incomplete-looking snippets.

For the first problem, an approach I can think of would be to actually use Parsoid to parse the whole lead section, so we handle templates properly (yet another alternative might be to just include the original article in an iframe).

For the second, it might make sense to not try to intelligently chop off the text, but rather use the full lead section, and perhaps limit how much gets displayed by just using some sort of [fade out](https://css-tricks.com/text-fade-read-more/) effect at the bottom.

**Comment by eggpi** [comment]
Made some progress on this over at the [de](https://github.com/eggpi/citationhunt/tree/de) branch. Using the API to convert snippets to HTML turned out to work well, but I'm still doing some cleanup. But it's really cool to see complicated templates being handled correctly:

<img width="1427" alt="screen shot 2016-11-05 at 21 35 51 pm" src="https://cloud.githubusercontent.com/assets/489134/20037944/8ebc7720-a422-11e6-945f-2f46ea8adb63.png">

In general, it's still pretty hackish, but it works. The commit message for 2a2969f25668af9fb01635668c34dc9ca78cefba has some items I need to look at, and the code itself needs some cleanup, but I think it's going in the right direction.

**Comment by Sadads** [comment]
I think thats a good first try first version, the email exchange with Barbara will hopefully unveil more.
