### ISSUE TITLE
Welsh translation

### ISSUE THREAD

**Issue by RichardNevell** [eggpi/citationhunt#61]
Welsh Wikipedia uses the template [Nodyn:Angen ffynhonnell](https://cy.wikipedia.org/wiki/Nodyn:Angen_ffynhonnell) to tag statements which need a citation. Used in less than 200 articles at the moment.

**Comment by jhsoby** [comment]
Hi @RichardNevell! To add Welsh, we'll need the following information for the configuration file. In addition you need to translate the interface [on Translatewiki](https://translatewiki.net/w/i.php?title=Special:Translate&group=citationhunt&language=cy&filter=%21translated&action=translate).

We need:
* The name of the category for articles with citation needed tags
* The name of the page where how to reference is explained
* The names of the templates that are used (which you have already provided)
* The name of the hidden category supercategory (same as English "Category:Hidden categories")

The most important thing is the translation in Translatewiki, the rest is pretty easy to figure out.

**Comment by eggpi** [comment]
Closing out incomplete, old language requests. Please reopen if you have the information we need!
