### ISSUE TITLE
Russian version

### ISSUE THREAD

**Issue by kaganer** [eggpi/citationhunt#77]
Please add Russian version. All translation in the translatewiki.net is done.

Some parameters for configuring it:

1. The name of the category for articles with citation needed tags:
https://ru.wikipedia.org/wiki/Категория:Википедия:Статьи_с_утверждениями_без_источников 
(with subcategories !)

2. The name of the page where how to reference is explained:
https://ru.wikipedia.org/wiki/Википедия:Ссылки_на_источники

3. The names of the templates that are used (which you have already provided):
https://ru.wikipedia.org/wiki/Шаблон:Нет_АИ
https://ru.wikipedia.org/wiki/Шаблон:Нет_АИ_2
https://ru.wikipedia.org/wiki/Шаблон:Нет_источника
https://ru.wikipedia.org/wiki/Шаблон:Нет_источника_2

4. The name of the hidden category supercategory (same as English "Category:Hidden categories"):
https://ru.wikipedia.org/wiki/Категория:Скрытые_категории

**Comment by eggpi** [comment]
I'm setting this up now, it should be live in a few minutes: https://tools.wmflabs.org/citationhunt/ru

Please give it a try and let me know if things are working and the snippets are generally readable. There will be a few broken ones because we don't support templates for the most part, but if there are too many, I can try to work around that.

Enjoy!

**Comment by kaganer** [comment]
Great thanks! All worked correctly!

Small notes:
1) I was a little corrected translations translatewiki.net
2) In  Russian there is THREE plural form for numeric values, not two. 
#1 for 1, 11, 21, etc., 
#2 for 2, 3, 4, 22, 23, 24, etc, 
#3 for all others. 
See more in https://translatewiki.net/wiki/Plural and https://translatewiki.net/wiki/Plural/Mediawiki_plural_rules

**Comment by eggpi** [comment]
Thanks for the links! I should really do this right. Filed #79 to track separately.
