### ISSUE TITLE
Romanian version

### ISSUE THREAD

**Issue by strainu** [eggpi/citationhunt#78]
Please add Romanian version. All translation in the translatewiki.net is done.

Some parameters for configuring it:

 - The name of the category for articles with citation needed tags: https://ro.wikipedia.org/wiki/Categorie:Articole_care_necesit%C4%83_cit%C4%83ri_suplimentare
- The name of the page where how to reference is explained: https://ro.wikipedia.org/wiki/Wikipedia:Citarea_surselor
- The names of the templates that are used:
  - https://ro.wikipedia.org/wiki/Format:Necesit%C4%83_citare
  - https://ro.wikipedia.org/wiki/Format:Nc
- The name of the hidden category supercategory (same as English "Category:Hidden categories"):
   - https://ro.wikipedia.org/wiki/Categorie:Categorii_ascunse

Thanks!

**Comment by eggpi** [comment]
I'm setting this up now, should be live in a few minutes: https://tools.wmflabs.org/citationhunt/ro . Enjoy!
