### ISSUE TITLE
Add proper suport for plurals.

### ISSUE THREAD

**Issue by eggpi** [eggpi/citationhunt#79]
Some helpful links:

https://translatewiki.net/wiki/Plural
https://rxaviers.github.io/javascript-globalization/
https://www.mediawiki.org/wiki/Localisation#Be_aware_of_PLURAL_use_on_all_numbers
https://www.sitepoint.com/how-to-implement-internationalization-i18n-in-javascript/

Initially brought up by @kaganer on #77, but the issue probably already affects other languages.

**Comment by ricordisamoa** [comment]
http://babel.pocoo.org/en/latest/api/plural.html#babel.plural.to_javascript

**Comment by eggpi** [comment]
It looks like jquery.i18n was enough for our needs now. Support added on master, just need to get the translations updated now.
