### ISSUE TITLE
Add Malayalam Wikipedia in Citationhunt

### ISSUE THREAD

**Issue by Jameela-P** [eggpi/citationhunt#82]
https://translatewiki.net/w/i.php?title=Special:Translate&group=citationhunt&language=ml&filter=&action=proofread 
here I translated all strings in Malayalam. It is requested to add Malayalam Wikipedia in CitationHunt.

**Comment by jhsoby** [comment]
Hi @Jameela-P! To add Malayalam, we'll need the following information for the configuration file.

We need:

* The name of the category for articles with citation needed tags
* The name of the page where how to reference is explained
* The names of the templates that are used (equivalents of {{cite}} in enwiki)
* The name of the hidden category supercategory (same as English "Category:Hidden categories")

**Comment by Jameela-P** [comment]
Hi @jhsoby  here I mentioned all required information

•The name of the category for articles with citation needed tags

https://ml.wikipedia.org/wiki/വർഗ്ഗം:അവലംബം_ചേർക്കേണ്ട_വാചകങ്ങളുള്ള_ലേഖനങ്ങൾ

•The name of the page where how to reference is explained

https://ml.wikipedia.org/wiki/വിക്കിപീഡിയ:അവലംബങ്ങൾ_ഉദ്ധരിക്കേണ്ടതെങ്ങനെ

•The names of the templates that are used (equivalents of {{cite}} in enwiki)

https://ml.wikipedia.org/wiki/ഫലകം:തെളിവ്     (Template:Citation needed)

https://ml.wikipedia.org/wiki/വർഗ്ഗം:ആവശ്യത്തിന്_അവലംബമില്ലാത്ത_ലേഖനങ്ങൾ

•The name of the hidden category supercategory (same as English "Category:Hidden categories")

https://ml.wikipedia.org/wiki/വർഗ്ഗം:മറഞ്ഞിരിക്കുന്ന_വർഗ്ഗങ്ങൾ  ??

**Comment by eggpi** [comment]
Here you go: https://tools.wmflabs.org/citationhunt/ml . The Malayalam alphabet looks very pretty :)

You might want to review the translation for the text in the green button, it's about twice as large as the blue for me.
