### ISSUE TITLE
Traditional Chinese Translation

### ISSUE THREAD

**Issue by shangkuanlc** [eggpi/citationhunt#88]
Hi @jhsoby , 

I have reviewed the Traditional Chinese translation on translatewiki

we'll need the following information for the configuration file. In addition you need to translate the interface on Translatewiki. The [zh-hant](https://translatewiki.net/w/i.php?title=Special:Translate&action=proofread&group=citationhunt&language=zh-hant) one.

**Comment by eggpi** [comment]
Hi @shangkuanlc!

This is for https://zh-classical.wikipedia.org, correct?

We'll need at least the following information to configure Citation Hunt:

- The name of the category for articles with citation needed tags
- A page that explains how to add references
- The names of the templates that are used (equivalents of {{cite}} in enwiki). There is no need to give us names of templates that redirect to other templates, we can handle those :)
- The name of the hidden category supercategory (same as English "Category:Hidden categories")

There are also some optional links we can add, please see [these lines of the configuration](https://github.com/eggpi/citationhunt/blob/master/config.py#L123-L132). But the only items we actually need are the list above.

**Comment by shangkuanlc** [comment]
Hi @eggpi 

No, not the zh-classical, it's for https://zh.wikipedia.org. The classical Chinese Wikipedia is rather using really old like the ancient style to write. In https://zh.wikipedia.org there many chunk of variance, but the two main type are zh-hant (Traditional Chinese) and zh-hans (Simplified Chinese).

I am a bit confuse with the 4 points you need. Can you give me English or Japanese Wikipedia pages as the examples so I can make sure the things you are asking for? Thank you.

**Comment by takot** [comment]
Hi @shangkuanlc 

How about checking lines 560-581 in config.py?
```
    ja = dict(
        lang_name = '日本語',
        lang_dir = 'ltr',
        database = 'jawiki_p',
        wikipedia_domain = 'ja.wikipedia.org',

        beginners_link = 'https://ja.wikipedia.org/wiki/Wikipedia:出典を明記する',
        beginners_link_title = 'Wikipedia:出典を明記する',

        lead_section_policy_link = 'https://ja.wikipedia.org/wiki/Wikipedia:スタイルマニュアル_(導入部)#.E5.87.BA.E5.85.B8',

        lead_section_policy_link_title = '導入部の出典',

        citation_needed_category = '出典を必要とする記述のある記事',
        citation_needed_template = [
            '出典の明記',
            '要出典',
        ],
        citation_needed_template_name = '要出典',
        hidden_category = '隠しカテゴリ',

        snippet_max_size = 1000,
```

**Comment by shangkuanlc** [comment]
Hi @takot,

Thank you for the example. I have compared the two and here is the related link:

`zh-hant = dict(

lang_name = '繁體中文',

lang_dir = 'ltr',

database = 'zhwiki_p',

wikipedia_domain = 'zh.wikipedia.org',


beginners_link = 'https://zh.wikipedia.org/wiki/Wikipedia:列明来源',


beginners_link_title = 'Wikipedia:列明來源',







lead_section_policy_link = 'https://zh.wikipedia.org/wiki/Wikipedia:LEADCITE',


lead_section_policy_link_title = '序言章節的引用',




citation_needed_category = '有未列明來源語句的條目',






citation_needed_template = [
Unreferenced',
Fact',
],
citation_needed_template_name = '來源請求',

hidden_category = '隱藏分類',

snippet_max_size = 1000,
),`

Is this good?

**Comment by eggpi** [comment]
I guess so, I think I can try it on the weekend and let you know. Thanks!

**Comment by shangkuanlc** [comment]
You are welcome
:)

**Comment by shangkuanlc** [comment]
Hi, is everything OK? Let me know how it goes, thank you.

**Comment by eggpi** [comment]
Sorry, I haven't had a chance to try this yet. I haven't forgotten though, hopefully I'll do it this weekend!

**Comment by shangkuanlc** [comment]
I see, thanks for the reply!
Guilherme Gonçalves <notifications@github.com>於 2017年3月10日 週五，17:21寫道：

**Comment by eggpi** [comment]
Hey @shangkuanlc, I noticed that many of the pages in the 有未列明来源语句的条目 category that you provided don't actually use `{{ Unreferenced }}` or `{{ Fact }}`. Examples: [Comic World](https://zh.wikipedia.org/wiki/Comic_World) and [賈南風](https://zh.wikipedia.org/wiki/%E8%B3%88%E5%8D%97%E9%A2%A8).

They all seem to include `{{ vc }}`, so maybe that's how the 有未列明来源语句的条目 category is defined? If so, do you know of a category that tracks `{{ Fact }}` instead of `{{ vc }}`?

Anyway, I did manage to get this working, but we're only finding about 1000 snippets out of about 9000 pages in the 有未列明来源语句的条目 category,  so I'm wondering if that's the correct category. Here's a screenshot if you're curious (I haven't updated the server yet):

<img width="1424" alt="screen shot 2017-03-11 at 18 48 35 pm" src="https://cloud.githubusercontent.com/assets/489134/23825964/5ef338c8-068b-11e7-8b0d-19b8ac7f0a4d.png">

**Comment by fantasticfears** [comment]
Thanks for the awesome works!

As far as I can tell, `{{ vc }}` is a shortcut to `{{ verify credibility }}` which should be included in `Category:All articles lacking reliable references` when referenced. 

The category `有未列明来源语句的条目` does have many articles from these templates mentioned. It's more a community thing. The @shangkuanlc is perfectly right at this category. But the template exactly matches the `{{ citation needed }}` in enwiki which would be `{{ Fact }}`.

I'm confused for this:

> The names of the templates that are used (equivalents of {{cite}} in enwiki). There is no need to give us names of templates that redirect to other templates, we can handle those :)

Do you mean by `{{ citation needed }}` template?

**Comment by Artoria2e5** [comment]
Um, enwp's {{citation needed}} (cn, fact, whatever) does not take a positional parameter for uncited text like zhwp's does. They use a separate {{cnspan}} template for highlighting uncited text.

**Comment by fantasticfears** [comment]
Yeah, I think @eggpi is mentioning the equivalents of {{cn}} or {{cnspan}}. So for the zhwiki_p there's only `{{Fact}}` which spans over the text.

**Comment by eggpi** [comment]
Hi @fantasticfears and @Artoria2e5, thanks for replying!

> But the template exactly matches the {{ citation needed }} in enwiki which would be {{ Fact }}

Thanks for clarifying! There was a small problem in the config that was causing Citation Hunt to ignore `{{ Fact }}`, so that was the problem. The Japanese config was also affected (1b8556bba83ddbf327a39df31c47571bba8f2dd5). I see now that `有未列明来源语句的条目` is the correct category, as @shangkuanlc said!

> Do you mean by {{ citation needed }} template?

What I meant is that, if one template redirects to another, there's no need to put both templates in the config.

For example, in enwiki, we don't need to put both `{{ cn }}` and `{{ Citation needed }}` in the config, since `{{ cn }}` is just a redirect to `{{ Citation needed }}`. @shangkuanlc gave me the correct values, this is all right :)

**Comment by fantasticfears** [comment]
```python
zh-hant = dict(
    lang_name = '简体中文',
    lang_dir = 'ltr',
    database = 'zhwiki_p',
    wikipedia_domain = 'zh.wikipedia.org',
    beginners_link = 'https://zh.wikipedia.org/wiki/Wikipedia:列明来源',
    beginners_link_title = 'Wikipedia:列明来源',
    lead_section_policy_link = 'https://zh.wikipedia.org/wiki/Wikipedia:LEADCITE',
    lead_section_policy_link_title = '序言章节的引用',
    citation_needed_category = '有未列明來源語句的條目',
    citation_needed_templates = [
        'Fact',
    ],
    citation_needed_template_name = '來源請求',
    hidden_category = '隱藏分類',
    snippet_max_size = 1000,
)
```

This should be useful for Simplified Chinese.

**Comment by Artoria2e5** [comment]
@fantasticfears It appears that they are using a simple `zh` for both for now. Regarding Python identifiers, I guess all the `-` would have to be replaced with `_` if we are going to do a hans/hant split. And don't forget to [simplify the text](http://opencc.byvoid.com/) for hans...

```Python
    citation_needed_category = '有未列明来源语句的条目',
    citation_needed_template_name = '来源请求',
    hidden_category = '隐藏分类',
```

**Comment by fantasticfears** [comment]
Oops, I was sloppy with the `_`. If `citation_needed_category` points to the actual category and aims to retrieve data, it's the correct name. zhwiki's articles title can use both character sets but displayed differently.

**Comment by eggpi** [comment]
> It appears that they are using a simple zh for both in bb0c1c1

Yes, I was planning on just using zh, but it would be perfectly fine to have separate versions as well if that makes more sense! In fact, given the information @fantasticfears provided in #91, it might make more sense to just split zh-hans and zh-hant.

**Comment by Artoria2e5** [comment]
> citation_needed_category points to the actual category and aims to retrieve data, it's the correct name.

You are right. My fault.

> zhwiki's articles title can use both character sets but displayed based on user's locale.

Yeah, that whole languageconvertor magic rocks... But note that for API usage, the `converttitles` query parameter must be included to get that automatic redirection going.

**Comment by eggpi** [comment]
Just deployed this:

https://tools.wmflabs.org/citationhunt/zh_hant
https://tools.wmflabs.org/citationhunt/zh_hans

Thanks everyone!
