### ISSUE TITLE
Choose strings for the UI using the Accept-Language header.

### ISSUE THREAD

**Issue by eggpi** [eggpi/citationhunt#91]
Right now we [couple](https://github.com/eggpi/citationhunt/blob/4c3d3486c4094837de9029bdf22d1820701b73ef/config.py#L613-L615) the language config with the strings that will be used in the UI.

This doesn't make a lot of sense for Wikipedias where a single config applies to more than one language (e.g., zhwiki, for which we have zh-hant and zh-hans translations, or ptwiki, which we can serve using pt or pt-br).

We should undo that decoupling and allow `app.py` to request the strings dynamically based on the `Accept-Language` header. Flask-Babel has nice support for that, though it would be nice to look at alternatives if there are any.

**Comment by fantasticfears** [comment]
I know language variants implementation for zhwiki and a dev. The source wikitext in zhwiki can be a mixture stream of variants. When displayed, they will be mapped into the variant user specified. It actually has 4 variants. But the editors are familiar with this mixture source anyway. I believe it's better to leave it as it is in terms of the engineering effort. If there are many complains, you can reconsider.

`Accept-Language` is more complicated than that. Me for example. The weird thing happens when I uses English locale in my browser and asks for zh-hans.

**Comment by eggpi** [comment]
Thanks for commenting!

> When displayed, they will be mapped into the variant user specified.

Do you know how this mapping happens on Wikipedia? Can we use the MediaWiki API to make that conversion?

>  It would be just OK to request the rendered text based on the config.

Sorry, I'm a little confused with this suggestion.

In b811422fc4e83cff47b82c3d940df1a1bea6e76f, I am suggesting this behavior:

- If you go to tools.wmflabs.org/citationhunt (without the **zh**), and you have `zh-*` in your `Accept-Language`, you will get redirected to tools.wmflabs.org/citationhunt/**zh**.
- If you go to tools.wmflabs.org/citationhunt/**zh**:
  - If you have `zh-hans` in your `Accept-Language`, the interface will use the strings in [zh-hans.json](https://github.com/eggpi/citationhunt/blob/master/chstrings/zh-hans.json). Same for zh-hant. We only have zh-hans and zh-hant translations for the interface right now.
  - If you don't have any of those in your `Accept-Language`, we use `zh-hans.json`.

But that only changes the text in the interface (for example, the buttons). The Wikipedia text is the same in all cases and comes directly from the wikitext.

Do you think that is a bad idea?

I would still like to do something like that because of other locales (en/en-GB, pt/pt-br), but if it is a bad idea for zh, I will be happy to change it, of course.

**Comment by fantasticfears** [comment]
### API

[parse](https://www.mediawiki.org/wiki/API:Parsing_wikitext) can be used. For plaintext, [Extension:TextExtracts](https://www.mediawiki.org/wiki/Extension:TextExtracts) looks better.
The sort of undocumented API is `variant`. For example, appending `&varaint=zh-hans` or `&varaint=zh-hant` after parse api yields the page in Simplified Chinese and Traditional Chinese.
I have little experience in using this API but I hope I provide information you need.

### Accept language

The URL redirection and language selection makes sense for citationhunt. It's a great design!

Unfortunately it's tricky to explain the locale and variant matter in few sentences. This i18n and localization problem for Chinese is a complicated beast. Users have different locales, these are from ISO 639 series. There will be zh-HK, zh-SG. See the table in https://github.com/getnikola/nikola/issues/1637. The `variant` parameter can take those locales to render desirable text for the reader. Those are supported variants and an option for Chinese Wikipedia readers.

As of the interface language, it's too expensive to maintain. So there is only `zh-hans` and `zh-hant`. `zh-hans` includes the `zh-CN` and `zh-SG`. While `zh-hant` includes others. That's also the language interface for zhwiki. So the best interest for citationhunt would be support `zh-hans` and `zh-hant` as interface language.

> Sidenote: Those name are quite messed up in the practice. A lot of words sometimes are used interchangeably. Actual standard: http://www.rfc-editor.org/rfc/bcp/bcp47.txt 

So there are two different things here for citationhunt. The first is the interface language. A mapping from `zh-CN` to `zh-hans` is necessary. The other is the text retrieval. It depends the granularity you need. Requesting by `zh-hans` and `zh-hant` is certainly general and easy. Storing the `zh-CN`, `zh-TW`, etc.. and requesting the API gives a more accurate version but the questions come that how to allow the users to change the variant.

Hope it helps.

**Comment by eggpi** [comment]
Thank you so much for this explanation! It is definitely very helpful!

About using the API, I'm working on using `parse` to improve the text extraction (issue #81). We already do that for some languages, and I'm trying to enable it for French now, then Chinese will probably be next, using the `variant` parameter as you suggest.

Until then, the Chinese version will unfortunately just use the mixed characters from the wikicode in zhwiki.

> The first is the interface language. A mapping from zh-CN to zh-hans is necessary.

I think this will already happen due to b811422fc4e83cff47b82c3d940df1a1bea6e76f, because we use zh-hans by default. I can definitely implement the other mapping (zh-TW/zh-HK/zh-MO -> zh-hant) in the interface too, if that makes sense.

> The other is the text retrieval. It depends the granularity you need. Requesting by zh-hans and zh-hant is certainly general and easy.

For now, because we are not using the API for parsing in Chinese, all we get is the wikitext with the mixed characters. When we start using the API, we can have two separate versions serving data extracted with different `variant` API parameters (zh-hans and zh-hant).

The simplest way to do it would be to just have completely separate versions of Citation Hunt: tools.wmflabs.org/citationhunt/zh-hans and tools.wmflabs.org/citationhunt/zh-hant. But I'll think about this some more later, when we're actually ready to support both.

This is fascinating, thank you again for all of this information :)

**Comment by fantasticfears** [comment]
> I think this will already happen due to b811422, because we use zh-hans by default. I can definitely implement the other mapping (zh-TW/zh-HK/zh-MO -> zh-hant) in the interface too, if that makes sense.

Of course, that makes perfect sense. 

> The simplest way to do it would be to just have completely separate versions of Citation Hunt: tools.wmflabs.org/citationhunt/zh-hans and tools.wmflabs.org/citationhunt/zh-hant. But I'll think about this some more later, when we're actually ready to support both.

Treat zh-hans and zh-hant as two different languages will be just fine. Although I don't know much flask, if you need more eyes on the code, @ me for the pull request and I'll do the best I can do
