### ISSUE TITLE
Mobile-friendly UI

### ISSUE THREAD

**Issue by takot** [eggpi/citationhunt#92]
This is just a popped-up idea: how about implementing mobile-friendly UI with some flavor of mobile frameworks such as Modernizr or jQuery Mobile or something alike. Once it's implemented, it would be easier to make it an app (with embedded browsing engine).

**Comment by shangkuanlc** [comment]
Yeah, that would be fun to bring the phone in a library and hunt citations.

;)
Takashi Ota <notifications@github.com>於 2017年3月15日 週三，21:02寫道：

**Comment by eggpi** [comment]
That would be nice. I haven't given much priority to mobile users yet because I don't know how often people actually edit on their mobile devices. I suspect it doesn't happen very often, but couldn't find statistics on a quick search.

We do get some mobile traffic though (en.m.wikipedia.org is one of the top referrers), so it would be nice to make sure citation hunt looks good in those cases, I just haven't had the time to do it yet.

@takot would you perhaps be interested in working on this? I'll be happy to discuss more details and review pull requests if you are!

**Comment by jessamynwest** [comment]
A responsive design might also make it look sleeker on desktop as well. Thumbs up for this suggestion.

**Comment by eggpi** [comment]
By the way, if we're talking redesign, it would be a good chance to address #97 as well. I do still think this is a good idea and I hope work on it soon (but it will still be after \#1Lib1Ref).

If anyone has more concrete thoughts on what this mobile / responsive UI could look like, I'd love to hear them -- especially if that includes mocks of some sort.

**Comment by eggpi** [comment]
An update: I finally started on this and I believe I'm making good progress, but I'm also learning Bootstrap as I go so work has still been a bit slow and I'm not planning on making very drastic UI changes yet, just making the UI look decent on smaller screens.

Code is in the "bootstrap" branch in this repository, and here's a few screenshots on different screen sizes using the Firefox developer tools:

- [My laptop, a Macbook Pro Retina Mid-2012](https://user-images.githubusercontent.com/489134/39540557-e16824b0-4e3a-11e8-81a1-a1f321675e02.png)
- [iPad Air 2](https://user-images.githubusercontent.com/489134/39540610-0e643e40-4e3b-11e8-9ee6-38b64cc5d5b0.png)
- [Nexus 5 phone, portrait initial view](https://user-images.githubusercontent.com/489134/39540648-2bd6e6a8-4e3b-11e8-85fe-21b7e75b7965.png), and [after scrolling](https://user-images.githubusercontent.com/489134/39540708-61547548-4e3b-11e8-8872-3777664f7d07.png)
- [Nexus 5 landscape, initial view](https://user-images.githubusercontent.com/489134/39540756-884be3c0-4e3b-11e8-9573-41837d1252d5.png), and [after scrolling](https://user-images.githubusercontent.com/489134/39540770-92a81456-4e3b-11e8-8b51-28db4024a9c7.png)

**Comment by eggpi** [comment]
OK, there are still a couple of quirks in this new UI, but I'm mostly fine with it so I've merged the branch and deployed it to Toolforge. Please give it a try and do file issues for things that bother you.

@takot Thanks for suggesting this btw, I had to learn some very useful stuff to do this :)

**Comment by takot** [comment]
Thanks @eggpi for making this happen! I will check it soon!
