### ISSUE TITLE
 Add Portuguese Wikipedia in Citationhunt

### ISSUE THREAD

**Issue by henriquecrang** [eggpi/citationhunt#95]
I would like to have CitationHunt running for Portuguese Wikipedia. All the strings on translatewiki.net are already translated and I have already maped this things:

* The name of the category for articles with citation needed tags
Categoria:!Artigos_que_carecem_de_fontes

* The name of the page where how to reference is explained
Ajuda:Tutorial/Referência

* The names of the templates that are used (equivalents of {{cite}} in enwiki)
Predefinição:Citar

* The name of the hidden category supercategory (same as English "Category:Hidden categories")
Categoria:!Categorias_ocultas

What should I do next?

**Comment by eggpi** [comment]
Hey, this is great!

If you'd like to try this yourself, the next step is to add this information to [config.py](https://github.com/eggpi/citationhunt/blob/master/config.py) and try it out by setting up a [local instance](https://github.com/eggpi/citationhunt/blob/master/CONTRIBUTING.md#setting-up-a-local-citation-hunt). If everything looks fine, just send me a pull request (example: #83) please.
